name: TO

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hello there! Welcome to Kulkat's server! We have a few rules that you must agree to. By clicking off of this, you agree to the TOS"
        pr-message: "Hello there! Welcome to Kulkat's server! We have a few rules that you must agree to. By clicking off of this, you agree to the TOS"
